import { FloorPlan, Point, Room, RoomChange, WallSide } from "./types/floorPlan";
import { areasConserve, BEDROOM_MIN_SQM, ENSUITE_SHOWER_MIN_M, ENSUITE_TARGET_SQM, pointInPolygon, polygonArea, polygonContainsPolygon, polygonSelfIntersects, sqmForPolygon, validateBedroomGeometry, validatePolygon } from "./geometryValidation";

type Corner = { sideX: "left" | "right"; sideY: "top" | "bottom" };
type Bounds = { x: number; y: number; width: number; height: number };
const ENSUITE_MIN_PRACTICAL_SQM = 1.8;
const normalise = (value?: string) => String(value || "").toLowerCase().replace(/\s+/g, "");
function noOp(current: string, requested: string): boolean { return !requested || normalise(current) === normalise(requested); }
function actionType(action?: string): string | undefined { switch (normalise(action)) { case "converttobedroom": return "bedroom"; case "converttokitchen": return "kitchen"; case "converttobathroom": return "bathroom"; case "converttoensuite": return "ensuite"; default: return undefined; } }
function bounds(points: Point[]): Bounds { const xs = points.map(p => p.x), ys = points.map(p => p.y); const x = Math.min(...xs), y = Math.min(...ys); return { x, y, width: Math.max(...xs) - x, height: Math.max(...ys) - y }; }
function windowWalls(room: Room): WallSide[] { return Array.from(new Set((room.windows || []).map(w => w.wall))); }
function doorWalls(room: Room): WallSide[] { return Array.from(new Set((room.doors || []).map(d => d.wall))); }
function openingIntervals(room: Room, kind: "door" | "window") { const openings = kind === "door" ? room.doors || [] : room.windows || []; return openings.map(opening => { const horizontal = opening.wall === "top" || opening.wall === "bottom"; const startWall = horizontal ? room.x : room.y, endWall = horizontal ? room.x + room.width : room.y + room.height; const start = Number(opening.start), end = Number(opening.end); if (Number.isFinite(start) && Number.isFinite(end) && end > start) return { wall: opening.wall, start, end, exact: true }; const span = endWall - startWall, reserve = Math.min(span * 0.30, 120), centre = (startWall + endWall) / 2; return { wall: opening.wall, start: centre - reserve / 2, end: centre + reserve / 2, exact: false }; }); }
function principalWindowWalls(room: Room): Set<WallSide> { const walls = windowWalls(room); if (!walls.length) return new Set(); const length = (wall: WallSide) => openingIntervals(room, "window").filter(o => o.wall === wall).reduce((sum, o) => sum + (o.end - o.start), 0) || (wall === "top" || wall === "bottom" ? room.width : room.height); const longest = Math.max(...walls.map(length)); return new Set(walls.filter(w => length(w) >= longest * 0.75)); }
function openingWallBlocked(room: Room, cut: Bounds): boolean { const edges: Array<[WallSide, boolean]> = [["top", Math.abs(cut.y - room.y) <= 2], ["bottom", Math.abs(cut.y + cut.height - (room.y + room.height)) <= 2], ["left", Math.abs(cut.x - room.x) <= 2], ["right", Math.abs(cut.x + cut.width - (room.x + room.width)) <= 2]]; return edges.some(([wall, at]) => at && openingIntervals(room, "door").some(o => { if (o.wall !== wall) return false; const start = wall === "top" || wall === "bottom" ? cut.x : cut.y; const end = wall === "top" || wall === "bottom" ? cut.x + cut.width : cut.y + cut.height; return Math.max(start, o.start) < Math.min(end, o.end); })); }
function preserveOpenings(room: Room, remainder: Point[]) { const survives = (wall: WallSide, start?: number, end?: number) => { const horizontal = wall === "top" || wall === "bottom", target = wall === "top" ? room.y : wall === "bottom" ? room.y + room.height : wall === "left" ? room.x : room.x + room.width; const min = Number.isFinite(start) ? Number(start) : horizontal ? room.x : room.y, max = Number.isFinite(end) ? Number(end) : horizontal ? room.x + room.width : room.y + room.height; return remainder.some((p, i) => { const q = remainder[(i + 1) % remainder.length]; const sameWall = horizontal ? Math.abs(p.y - q.y) <= 2 && Math.abs(p.y - target) <= 3 : Math.abs(p.x - q.x) <= 2 && Math.abs(p.x - target) <= 3; if (!sameWall) return false; const a = horizontal ? Math.min(p.x, q.x) : Math.min(p.y, q.y), b = horizontal ? Math.max(p.x, q.x) : Math.max(p.y, q.y); return Math.max(a, min) < Math.min(b, max); }); }; return { windows: (room.windows || []).filter(w => survives(w.wall, w.start, w.end)), doors: (room.doors || []).filter(d => survives(d.wall, d.start, d.end)) }; }
function clip(points: Point[], axis: "x" | "y", threshold: number, greater: boolean): Point[] | undefined { if (points.length < 3) return undefined; const inside = (p: Point) => greater ? p[axis] >= threshold : p[axis] <= threshold; const intersection = (a: Point, b: Point): Point => { const delta = b[axis] - a[axis], t = Math.abs(delta) < 1e-9 ? 0 : (threshold - a[axis]) / delta; return axis === "x" ? { x: threshold, y: a.y + (b.y - a.y) * t } : { x: a.x + (b.x - a.x) * t, y: threshold }; }; const result: Point[] = []; for (let i = 0; i < points.length; i++) { const a = points[(i - 1 + points.length) % points.length], b = points[i], aInside = inside(a), bInside = inside(b); if (aInside !== bInside) result.push(intersection(a, b)); if (bInside) result.push(b); } return result.length >= 3 ? result : undefined; }
function subtractCornerRectangle(source: Point[], cut: Bounds): Point[] | undefined { if (source.length !== 4) return undefined; const minX = Math.min(...source.map(p => p.x)), maxX = Math.max(...source.map(p => p.x)), minY = Math.min(...source.map(p => p.y)), maxY = Math.max(...source.map(p => p.y)); const right = cut.x + cut.width, bottom = cut.y + cut.height, EPS = 1e-6; const eq = (a: number, b: number) => Math.abs(a - b) <= EPS; if (eq(cut.x, minX) && eq(cut.y, minY)) return [{ x: right, y: minY }, { x: maxX, y: minY }, { x: maxX, y: maxY }, { x: minX, y: maxY }, { x: minX, y: bottom }, { x: right, y: bottom }]; if (eq(right, maxX) && eq(cut.y, minY)) return [{ x: minX, y: minY }, { x: cut.x, y: minY }, { x: cut.x, y: bottom }, { x: maxX, y: bottom }, { x: maxX, y: maxY }, { x: minX, y: maxY }]; if (eq(cut.x, minX) && eq(bottom, maxY)) return [{ x: minX, y: minY }, { x: maxX, y: minY }, { x: maxX, y: maxY }, { x: right, y: maxY }, { x: right, y: cut.y }, { x: minX, y: cut.y }]; if (eq(right, maxX) && eq(bottom, maxY)) return [{ x: minX, y: minY }, { x: cut.x, y: minY }, { x: cut.x, y: cut.y }, { x: maxX, y: cut.y }, { x: maxX, y: maxY }, { x: minX, y: maxY }]; return undefined; }
function carveCorner(source: Point[], cut: Bounds, corner: Corner): Point[] | undefined { if (!validatePolygon(source).valid) return undefined; const exact = subtractCornerRectangle(source, cut); if (exact && validatePolygon(exact).valid) return exact; if (source.length === 4) return undefined; let result: Point[] | undefined = structuredClone(source); const minX = corner.sideX === "left" ? cut.x + cut.width : undefined, maxX = corner.sideX === "right" ? cut.x : undefined, minY = corner.sideY === "top" ? cut.y + cut.height : undefined, maxY = corner.sideY === "bottom" ? cut.y : undefined; if (minX !== undefined) result = result && clip(result, "x", minX, true); if (maxX !== undefined) result = result && clip(result, "x", maxX, false); if (minY !== undefined) result = result && clip(result, "y", minY, true); if (maxY !== undefined) result = result && clip(result, "y", maxY, false); return result && validatePolygon(result).valid ? result : undefined; }
function childRoom(source: Room, polygon: Point[], type: string, name: string, notes: string): Room { const b = bounds(polygon); return { ...structuredClone(source), id: `${source.id}-split-2`, name, type, x: b.x, y: b.y, width: b.width, height: b.height, polygon, windows: [], doors: [], adjacentRooms: [source.id], approxAreaSqm: 0, notes: [source.notes, notes].filter(Boolean).join(";"), confidence: "geometry-proposed" }; }
function splitRoomGeometry(floor: { rooms: Room[] }, room: Room, change: RoomChange): boolean { const isEnsuite = /ensuite|bath|shower/i.test(String(change.split?.secondType || "")); if (isEnsuite) return addEnsuiteGeometry(floor, room, change); const original = structuredClone(room), polygon = original.polygon; if (!polygon || polygon.length < 3) return false; const direction = change.split?.direction || (windowWalls(room).some(w => w === "top" || w === "bottom") ? "horizontal" : "vertical"), ratio = Number.isFinite(Number(change.split?.firstRatio)) ? Math.max(0.35, Math.min(0.65, Number(change.split?.firstRatio))) : 0.5, threshold = direction === "horizontal" ? room.y + room.height * ratio : room.x + room.width * ratio;
  // A split is only valid when the openings parallel to the cut do not straddle it. This prevents one doorway from being inherited by both rooms while allowing the normal two-door/two-window split pattern.
  const parallelWalls = direction === "horizontal" ? new Set<WallSide>(["left", "right"]) : new Set<WallSide>(["top", "bottom"]);
  if (openingIntervals(original, "door").some(o => parallelWalls.has(o.wall) && o.start < threshold - 1e-6 && o.end > threshold + 1e-6)) return false;
  const cutAxis = direction === "horizontal" ? "y" : "x";
  const first = clip(polygon, cutAxis, threshold, false), second = clip(polygon, cutAxis, threshold, true); if (!first || !second || polygonSelfIntersects(first) || polygonSelfIntersects(second)) return false; const firstOpen = preserveOpenings(original, first), secondOpen = preserveOpenings(original, second), firstRoom: Room = { ...original, polygon: first, type: "bedroom", name: change.split?.firstName || original.name, windows: firstOpen.windows, doors: firstOpen.doors }, secondRoom: Room = { ...original, id: `${original.id}-split-2`, polygon: second, type: "bedroom", name: change.split?.secondName || "Bedroom", windows: secondOpen.windows, doors: secondOpen.doors }; if (!validateBedroomGeometry(firstRoom).valid || !validateBedroomGeometry(secondRoom).valid || !areasConserve(original, first, second)) return false; const firstBounds = bounds(first); Object.assign(room, firstRoom, { x: firstBounds.x, y: firstBounds.y, width: firstBounds.width, height: firstBounds.height, approxAreaSqm: Number(sqmForPolygon(original, first).toFixed(2)), confidence: "geometry-proposed" }); const child = childRoom(original, second, "bedroom", change.split?.secondName || "Bedroom", "Validated genuine room split"); child.windows = secondOpen.windows; child.doors = secondOpen.doors; child.approxAreaSqm = Number(sqmForPolygon(original, second).toFixed(2)); floor.rooms.push(child); return true; }
function candidateCorners(room: Room): Corner[] { const windows = new Set(windowWalls(room)), principal = principalWindowWalls(room), doors = new Set(doorWalls(room)), corners: Corner[] = [{ sideX: "left", sideY: "top" }, { sideX: "right", sideY: "top" }, { sideX: "left", sideY: "bottom" }, { sideX: "right", sideY: "bottom" }]; const score = (c: Corner) => { const x = c.sideX as WallSide, y = c.sideY as WallSide; return (windows.has(x) || windows.has(y) ? -1000 : 100) + (principal.has(x) || principal.has(y) ? -2000 : 0) + (doors.has(x) || doors.has(y) ? -150 : 0); }; return corners.sort((a, b) => score(b) - score(a)); }
function buildCornerRect(room: Room, corner: Corner, width: number, height: number): Bounds { return { x: corner.sideX === "right" ? room.x + room.width - width : room.x, y: corner.sideY === "bottom" ? room.y + room.height - height : room.y, width, height }; }
function findEnsuite(room: Room): { polygon: Point[]; remainder: Point[]; areaSqm: number } | undefined { if (!room.polygon?.length || !validateBedroomGeometry(room).valid) return undefined; const sourcePx = polygonArea(room.polygon), sourceSqm = Number(room.approxAreaSqm || 0), metresPerPixel = sourcePx > 0 && sourceSqm > 0 ? Math.sqrt(sourceSqm / sourcePx) : 0; const fractions = [0.24,0.28,0.32,0.36,0.40,0.44,0.46,0.48,0.50,0.52,0.54,0.56]; const candidates: Array<{ polygon: Point[]; remainder: Point[]; areaSqm: number; score: number }> = []; for (const corner of candidateCorners(room)) for (const wf of fractions) for (const hf of fractions) { const cut = buildCornerRect(room, corner, room.width * wf, room.height * hf); if (openingWallBlocked(room, cut)) continue; const polygon: Point[] = [{ x: cut.x, y: cut.y }, { x: cut.x + cut.width, y: cut.y }, { x: cut.x + cut.width, y: cut.y + cut.height }, { x: cut.x, y: cut.y + cut.height }]; if (!polygonContainsPolygon(room.polygon, polygon)) continue; const remainder = carveCorner(room.polygon, cut, corner); if (!remainder || !areasConserve(room, remainder, polygon)) continue; const openings = preserveOpenings(room, remainder), principal = principalWindowWalls(room); if (!openings.doors?.length || (principal.size && !Array.from(principal).every(w => (openings.windows || []).some(x => x.wall === w)))) continue; const bedroomRemainder = { ...structuredClone(room), polygon: remainder, windows: openings.windows, doors: openings.doors, type: "bedroom" }; if (!validateBedroomGeometry(bedroomRemainder).valid) continue; const ensuiteArea = sqmForPolygon(room, polygon); if (ensuiteArea < ENSUITE_MIN_PRACTICAL_SQM) continue; const widthM = room.approxWidthM && room.width ? cut.width * room.approxWidthM / room.width : cut.width * metresPerPixel, heightM = room.approxDepthM && room.height ? cut.height * room.approxDepthM / room.height : cut.height * metresPerPixel; if (widthM < ENSUITE_SHOWER_MIN_M || heightM < ENSUITE_SHOWER_MIN_M) continue; const score = Math.abs(ensuiteArea - ENSUITE_TARGET_SQM); candidates.push({ polygon, remainder, areaSqm: ensuiteArea, score }); } candidates.sort((a,b) => a.score - b.score); return candidates[0] ? { polygon: candidates[0].polygon, remainder: candidates[0].remainder, areaSqm: candidates[0].areaSqm } : undefined; }
function addEnsuiteGeometry(floor: { rooms: Room[] }, room: Room, change: RoomChange): boolean { const candidate = findEnsuite(room); if (!candidate) return false; const original = structuredClone(room), openings = preserveOpenings(original, candidate.remainder), b = bounds(candidate.remainder); const remainder: Room = { ...original, polygon: candidate.remainder, x: b.x, y: b.y, width: b.width, height: b.height, windows: openings.windows, doors: openings.doors, type: "bedroom", name: change.split?.firstName || original.name }; const checked = validateBedroomGeometry(remainder); if (!checked.valid || !areasConserve(original, candidate.remainder, candidate.polygon)) return false; Object.assign(room, remainder, { approxAreaSqm: Number(checked.areaSqm.toFixed(2)), confidence: "geometry-proposed" }); const child = childRoom(original, candidate.polygon, "ensuite", "En-suite", `Real geometry carved from ${original.id}`); child.approxAreaSqm = Number(candidate.areaSqm.toFixed(2)); floor.rooms.push(child); return true; }
function applySimple(room: Room, change: RoomChange): boolean { const requested = String(change.newType || actionType(change.action) || "").toLowerCase(); if (!requested || noOp(room.type || "", requested)) return false; room.type = change.newType || actionType(change.action) || room.type; if (change.newName) room.name = change.newName; else if (requested === "bedroom" && !/bedroom/i.test(room.name)) room.name = "Proposed Bedroom"; if (change.reason) room.notes = [room.notes, change.reason].filter(Boolean).join(";"); return true; }
export function applyRoomChanges(floorPlan: FloorPlan, changes: RoomChange[]): FloorPlan { const updated = structuredClone(floorPlan); for (const change of changes || []) { if (!change?.roomId) continue; for (const floor of updated.floors) { const room = floor.rooms.find(r => r.id === change.roomId); if (!room) continue; const action = normalise(change.action), requested = String(change.newType || actionType(change.action) || "").toLowerCase(); if (action === "nochange" && !requested) break; if (action === "splitroom" || action === "split") { splitRoomGeometry(floor, room, change); break; } if (requested.includes("ensuite") || action === "converttoensuite") { if (/bedroom/i.test(room.type)) addEnsuiteGeometry(floor, room, change); break; } if (requested) applySimple(room, change); break; } } return updated; }
export function bedroomGeometryIsValid(room: Room): boolean { return validateBedroomGeometry(room).valid; }
