import { FloorPlan, Point, Room, RoomChange, WallSide } from "./types/floorPlan";
import { areasConserve, BEDROOM_MIN_SQM, ENSUITE_SHOWER_MIN_M, ENSUITE_TARGET_SQM, polygonArea, polygonContainsPolygon, polygonSelfIntersects, sqmForPolygon, validateBedroomGeometry, validatePolygon } from "./geometryValidation";

type Corner = { sideX: "left" | "right"; sideY: "top" | "bottom" };
type Bounds = { x: number; y: number; width: number; height: number };
const ENSUITE_MIN_PRACTICAL_SQM = 1.8;
const normalise = (value?: string) => String(value || "").toLowerCase().replace(/\s+/g, "");
const noOp = (current: string, requested: string) => !requested || normalise(current) === normalise(requested);
const actionType = (action?: string): string | undefined => { switch (normalise(action)) { case "converttobedroom": return "bedroom"; case "converttokitchen": return "kitchen"; case "converttobathroom": return "bathroom"; case "converttoensuite": return "ensuite"; default: return undefined; } };
const bounds = (points: Point[]): Bounds => { const xs = points.map(p => p.x), ys = points.map(p => p.y); const x = Math.min(...xs), y = Math.min(...ys); return { x, y, width: Math.max(...xs) - x, height: Math.max(...ys) - y }; };
const windowWalls = (room: Room): WallSide[] => Array.from(new Set((room.windows || []).map(w => w.wall)));
const doorWalls = (room: Room): WallSide[] => Array.from(new Set((room.doors || []).map(d => d.wall)));
function openingIntervals(room: Room, kind: "door" | "window") { const openings = kind === "door" ? room.doors || [] : room.windows || []; return openings.map(o => { const horizontal = o.wall === "top" || o.wall === "bottom"; const startWall = horizontal ? room.x : room.y, endWall = horizontal ? room.x + room.width : room.y + room.height; const start = Number(o.start), end = Number(o.end); if (Number.isFinite(start) && Number.isFinite(end) && end > start) return { wall: o.wall, start, end }; const span = endWall - startWall, reserve = Math.min(span * 0.3, 120), centre = (startWall + endWall) / 2; return { wall: o.wall, start: centre - reserve / 2, end: centre + reserve / 2 }; }); }
function principalWindowWalls(room: Room): Set<WallSide> { const walls = windowWalls(room); if (!walls.length) return new Set(); const length = (w: WallSide) => openingIntervals(room, "window").filter(o => o.wall === w).reduce((s, o) => s + o.end - o.start, 0) || (w === "top" || w === "bottom" ? room.width : room.height); const longest = Math.max(...walls.map(length)); return new Set(walls.filter(w => length(w) >= longest * 0.75)); }
function openingWallBlocked(room: Room, cut: Bounds) { const edges: Array<[WallSide, boolean]> = [["top", Math.abs(cut.y - room.y) <= 2], ["bottom", Math.abs(cut.y + cut.height - (room.y + room.height)) <= 2], ["left", Math.abs(cut.x - room.x) <= 2], ["right", Math.abs(cut.x + cut.width - (room.x + room.width)) <= 2]]; return edges.some(([wall, at]) => at && openingIntervals(room, "door").some(o => { if (o.wall !== wall) return false; const start = wall === "top" || wall === "bottom" ? cut.x : cut.y; const end = wall === "top" || wall === "bottom" ? cut.x + cut.width : cut.y + cut.height; return Math.max(start, o.start) < Math.min(end, o.end); })); }
function preserveOpenings(room: Room, remainder: Point[]) { const survives = (wall: WallSide, start?: number, end?: number) => { const horizontal = wall === "top" || wall === "bottom", target = wall === "top" ? room.y : wall === "bottom" ? room.y + room.height : wall === "left" ? room.x : room.x + room.width; const min = Number.isFinite(start) ? Number(start) : horizontal ? room.x : room.y, max = Number.isFinite(end) ? Number(end) : horizontal ? room.x + room.width : room.y + room.height; return remainder.some((p, i) => { const q = remainder[(i + 1) % remainder.length]; const same = horizontal ? Math.abs(p.y - q.y) <= 2 && Math.abs(p.y - target) <= 3 : Math.abs(p.x - q.x) <= 2 && Math.abs(p.x - target) <= 3; if (!same) return false; const a = horizontal ? Math.min(p.x, q.x) : Math.min(p.y, q.y), b = horizontal ? Math.max(p.x, q.x) : Math.max(p.y, q.y); return Math.max(a, min) < Math.min(b, max); }); }; return { windows: (room.windows || []).filter(w => survives(w.wall, w.start, w.end)), doors: (room.doors || []).filter(d => survives(d.wall, d.start, d.end)) }; }
function clip(points: Point[], axis: "x" | "y", threshold: number, greater: boolean): Point[] | undefined { if (points.length < 3) return; const inside = (p: Point) => greater ? p[axis] >= threshold : p[axis] <= threshold; const intersection = (a: Point, b: Point): Point => { const d = b[axis] - a[axis], t = Math.abs(d) < 1e-9 ? 0 : (threshold - a[axis]) / d; return axis === "x" ? { x: threshold, y: a.y + (b.y - a.y) * t } : { x: a.x + (b.x - a.x) * t, y: threshold }; }; const out: Point[] = []; for (let i = 0; i < points.length; i++) { const a = points[(i - 1 + points.length) % points.length], b = points[i], ai = inside(a), bi = inside(b); if (ai !== bi) out.push(intersection(a, b)); if (bi) out.push(b); } return out.length >= 3 ? out : undefined; }
function carveCorner(source: Point[], cut: Bounds, corner: Corner): Point[] | undefined { if (!validatePolygon(source).valid) return; if (source.length !== 4) return; const minX = Math.min(...source.map(p => p.x)), maxX = Math.max(...source.map(p => p.x)), minY = Math.min(...source.map(p => p.y)), maxY = Math.max(...source.map(p => p.y)); const r = cut.x + cut.width, b = cut.y + cut.height, eq = (a: number, z: number) => Math.abs(a - z) <= 1e-6; let result: Point[] | undefined; if (corner.sideX === "left" && corner.sideY === "top" && eq(cut.x,minX) && eq(cut.y,minY)) result=[{x:r,y:minY},{x:maxX,y:minY},{x:maxX,y:maxY},{x:minX,y:maxY},{x:minX,y:b},{x:r,y:b}]; else if (corner.sideX === "right" && corner.sideY === "top" && eq(r,maxX) && eq(cut.y,minY)) result=[{x:minX,y:minY},{x:cut.x,y:minY},{x:cut.x,y:b},{x:maxX,y:b},{x:maxX,y:maxY},{x:minX,y:maxY}]; else if (corner.sideX === "left" && corner.sideY === "bottom" && eq(cut.x,minX) && eq(b,maxY)) result=[{x:minX,y:minY},{x:maxX,y:minY},{x:maxX,y:maxY},{x:r,y:maxY},{x:r,y:cut.y},{x:minX,y:cut.y}]; else if (corner.sideX === "right" && corner.sideY === "bottom" && eq(r,maxX) && eq(b,maxY)) result=[{x:minX,y:minY},{x:cut.x,y:minY},{x:cut.x,y:cut.y},{x:maxX,y:cut.y},{x:maxX,y:maxY},{x:minX,y:maxY}]; return result && validatePolygon(result).valid ? result : undefined; }
function childRoom(source: Room, polygon: Point[], type: string, name: string, notes: string): Room { const b = bounds(polygon); return { ...structuredClone(source), id: `${source.id}-split-2`, name, type, x:b.x,y:b.y,width:b.width,height:b.height,polygon,windows:[],doors:[],adjacentRooms:[source.id],approxAreaSqm:0,notes:[source.notes,notes].filter(Boolean).join(";"),confidence:"geometry-proposed" }; }
function splitRoomGeometry(floor: { rooms: Room[] }, room: Room, change: RoomChange): boolean { if (/ensuite|bath|shower/i.test(String(change.split?.secondType || ""))) return addEnsuiteGeometry(floor, room, change); const original=structuredClone(room), polygon=original.polygon; if(!polygon||polygon.length<3)return false; const direction=change.split?.direction || (windowWalls(room).some(w=>w==="top"||w==="bottom")?"horizontal":"vertical"), ratio=Number.isFinite(Number(change.split?.firstRatio))?Math.max(.35,Math.min(.65,Number(change.split?.firstRatio))):.5, threshold=direction==="horizontal"?room.y+room.height*ratio:room.x+room.width*ratio, axis=direction==="horizontal"?"y":"x"; const first=clip(polygon,axis,threshold,false),second=clip(polygon,axis,threshold,true); if(!first||!second||polygonSelfIntersects(first)||polygonSelfIntersects(second))return false; const fo=preserveOpenings(original,first),so=preserveOpenings(original,second); const r1:Room={...original,polygon:first,type:"bedroom",name:change.split?.firstName||original.name,windows:fo.windows,doors:fo.doors},r2:Room={...original,id:`${original.id}-split-2`,polygon:second,type:"bedroom",name:change.split?.secondName||"Bedroom",windows:so.windows,doors:so.doors}; if(!validateBedroomGeometry(r1).valid||!validateBedroomGeometry(r2).valid||!areasConserve(original,first,second))return false; const b=bounds(first); Object.assign(room,r1,{x:b.x,y:b.y,width:b.width,height:b.height,approxAreaSqm:Number(sqmForPolygon(original,first).toFixed(2)),confidence:"geometry-proposed"}); const child=childRoom(original,second,"bedroom",change.split?.secondName||"Bedroom","Validated genuine room split"); child.windows=so.windows;child.doors=so.doors;child.approxAreaSqm=Number(sqmForPolygon(original,second).toFixed(2));floor.rooms.push(child);return true; }
function candidateCorners(room: Room): Corner[] { const windows=new Set(windowWalls(room)),principal=principalWindowWalls(room),doors=new Set(doorWalls(room)); const cs:Corner[]=[{sideX:"left",sideY:"top"},{sideX:"right",sideY:"top"},{sideX:"left",sideY:"bottom"},{sideX:"right",sideY:"bottom"}]; const score=(c:Corner)=>(windows.has(c.sideX as WallSide)||windows.has(c.sideY as WallSide)?-1000:100)+(principal.has(c.sideX as WallSide)||principal.has(c.sideY as WallSide)?-2000:0)+(doors.has(c.sideX as WallSide)||doors.has(c.sideY as WallSide)?-150:0); return cs.sort((a,b)=>score(b)-score(a)); }
function buildCornerRect(room: Room, corner: Corner, width: number, height: number): Bounds { return {x:corner.sideX==="right"?room.x+room.width-width:room.x,y:corner.sideY==="bottom"?room.y+room.height-height:room.y,width,height}; }
function findEnsuite(room: Room) { if(!room.polygon?.length||!validateBedroomGeometry(room).valid)return; const sourcePx=polygonArea(room.polygon), sourceSqm=Number(room.approxAreaSqm||0), mpp=sourcePx>0&&sourceSqm>0?Math.sqrt(sourceSqm/sourcePx):0; const fractions=[.24,.28,.32,.36,.40,.44,.46,.48,.50,.52,.54,.56]; const candidates:Array<{polygon:Point[];remainder:Point[];areaSqm:number;score:number}>=[]; for(const corner of candidateCorners(room))for(const wf of fractions)for(const hf of fractions){const cut=buildCornerRect(room,corner,room.width*wf,room.height*hf);if(openingWallBlocked(room,cut))continue;const poly:Point[]=[{x:cut.x,y:cut.y},{x:cut.x+cut.width,y:cut.y},{x:cut.x+cut.width,y:cut.y+cut.height},{x:cut.x,y:cut.y+cut.height}];if(!polygonContainsPolygon(room.polygon,poly))continue;const remainder=carveCorner(room.polygon,cut,corner);if(!remainder||!areasConserve(room,remainder,poly))continue;const openings=preserveOpenings(room,remainder),principal=principalWindowWalls(room);if(!openings.doors.length||(principal.size&&!Array.from(principal).every(w=>(openings.windows||[]).some(x=>x.wall===w))))continue;const br={...structuredClone(room),polygon:remainder,windows:openings.windows,doors:openings.doors,approxAreaSqm:sqmForPolygon(room,remainder)};if(!validateBedroomGeometry(br).valid)continue;const area=sqmForPolygon(room,poly);if(area<ENSUITE_MIN_PRACTICAL_SQM)continue;const widthM=room.approxWidthM&&room.width?cut.width*room.approxWidthM/room.width:cut.width*mpp,heightM=room.approxDepthM&&room.height?cut.height*room.approxDepthM/room.height:cut.height*mpp;if(widthM<ENSUITE_SHOWER_MIN_M||heightM<ENSUITE_SHOWER_MIN_M)continue;candidates.push({polygon:poly,remainder,areaSqm:area,score:Math.abs(area-ENSUITE_TARGET_SQM)});}candidates.sort((a,b)=>a.score-b.score);return candidates[0]; }
function addEnsuiteGeometry(floor:{rooms:Room[]},room:Room,change:RoomChange):boolean {const candidate=findEnsuite(room);if(!candidate)return false;const original=structuredClone(room),remainderArea=sqmForPolygon(original,candidate.remainder),openings=preserveOpenings(original,candidate.remainder),b=bounds(candidate.remainder);const updated:Room={...original,polygon:candidate.remainder,x:b.x,y:b.y,width:b.width,height:b.height,approxAreaSqm:Number(remainderArea.toFixed(2)),name:change.split?.firstName||original.name,type:"bedroom",windows:openings.windows,doors:openings.doors,notes:[original.notes,"Bedroom remainder after physically carved private ensuite"].filter(Boolean).join(";"),confidence:"geometry-proposed"};if(!validateBedroomGeometry(updated).valid)return false;Object.assign(room,updated);const child=childRoom(original,candidate.polygon,"ensuite",change.split?.secondName||"En-suite","Physically carved inside source bedroom polygon");child.approxAreaSqm=Number(candidate.areaSqm.toFixed(2));child.doors=[{wall:doorWalls(original)[0]||"top"}];floor.rooms.push(child);return true;}
export function applyRoomChanges(plan: FloorPlan, changes: RoomChange[]=[]): FloorPlan {const updated=structuredClone(plan);for(const change of changes){if(!change?.roomId||!change.action)continue;for(const floor of updated.floors){const room=floor.rooms.find(r=>r.id===change.roomId);if(!room)continue;const action=normalise(change.action),target=actionType(change.action)||change.newType;if(action==="splitroom"||action==="split"){splitRoomGeometry(floor,room,change);continue;}if(target==="ensuite"){addEnsuiteGeometry(floor,room,change);continue;}if(noOp(room.type,target||"")&&!action.includes("merge"))continue;if(target){room.type=target;room.name=change.newName||room.name;}}}return updated;}
export { noOp };
