import { FloorPlan, RoomChange, Point } from "./types/floorPlan";
import { polygonContainsPolygon } from "./geometryValidation";

function escapeXml(text: string): string { return String(text).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;"); }
function norm(value: unknown): string { return String(value || "").toLowerCase().replace(/[^a-z0-9]/g, ""); }
function isBedroom(room: any): boolean { return norm(`${room?.type || ""} ${room?.name || ""}`).includes("bedroom"); }
function isEnsuite(room: any): boolean { return /ensuite|en-suite/i.test(`${room?.type || ""} ${room?.name || ""}`); }
function polygonPoints(points?: Point[]): string | null { if (!points || points.length < 3) return null; return points.map(p => `${Number(p.x)},${Number(p.y)}`).join(" "); }
function roomCenter(room: any): { x: number; y: number } { const p=room?.polygon as Point[]|undefined; if(!p||p.length<3)return{x:Number(room.x)+Number(room.width)/2,y:Number(room.y)+Number(room.height)/2};let a2=0,cx=0,cy=0;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],cross=a.x*b.y-b.x*a.y;a2+=cross;cx+=(a.x+b.x)*cross;cy+=(a.y+b.y)*cross;}return Math.abs(a2)<1e-6?{x:Number(room.x)+Number(room.width)/2,y:Number(room.y)+Number(room.height)/2}:{x:cx/(3*a2),y:cy/(3*a2)}; }
function roomFill(room:any,floorIndex:number):string{if(isEnsuite(room))return"#38bdf8";return["#facc15","#86efac","#f0a3d7","#c4b5fd","#fdba74"][Math.max(0,floorIndex)%5];}
function renderRoom(room:any,label:string,kind:"bedroom"|"ensuite",floorIndex:number,clipId?:string):string{const points=polygonPoints(room?.polygon);if(!points)return"";const fill=roomFill(room,floorIndex),stroke=kind==="ensuite"?"#075985":"#334155",shape=`<polygon points="${points}" fill="${fill}" fill-opacity="0.58" stroke="${stroke}" stroke-width="5" vector-effect="non-scaling-stroke"/>`,center=roomCenter(room),w=Number(room.width),h=Number(room.height),font=Math.max(10,Math.min(20,Math.min(w,h)/5)),badge=Math.max(70,Math.min(145,label.length*10+28)),badgeH=Math.max(22,Math.min(38,h*.18)),bx=center.x-badge/2,by=center.y-badgeH/2,clip=clipId?` clip-path="url(#${clipId})"`:"";return`<g${clip}>${shape}<rect x="${bx}" y="${by}" width="${badge}" height="${badgeH}" rx="6" fill="${stroke}" fill-opacity="0.96"/><text x="${center.x}" y="${center.y+font*.34}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${font}" font-weight="800" fill="white">${escapeXml(label)}</text></g>`;}
function makeClipPath(id:string,room:any):string{const points=polygonPoints(room?.polygon);return points?`<clipPath id="${id}"><polygon points="${points}"/></clipPath>`:"";}
function baseId(id:string):string{return id.replace(/-split-2$/i,"");}
function sourceFor(room:any,originals:Map<string,any>):any|undefined{return originals.get(String(room?.id||"").trim().toLowerCase())||originals.get(baseId(String(room?.id||"").trim().toLowerCase()));}
function validAnchored(room:any,source:any):boolean{const p=room?.polygon as Point[]|undefined,sp=source?.polygon as Point[]|undefined;if(!p||p.length<3||!sp||sp.length<3)return false;return polygonContainsPolygon(sp,p);}

export function renderFloorPlan(original:FloorPlan,proposed:FloorPlan,originalImageDataUri:string,changes:RoomChange[]=[]):string{
 const width=original.metadata?.imageWidth??proposed.metadata?.imageWidth??1600,height=original.metadata?.imageHeight??proposed.metadata?.imageHeight??1200,originals=new Map<string,any>();for(const floor of original.floors)for(const room of floor.rooms)originals.set(String(room.id).trim().toLowerCase(),room);
 const defs:string[]=[],overlays:string[]=[],rendered=new Set<string>();const proposedBedrooms:Array<{room:any;floorIndex:number;id:string;source:any}>=[];const proposedEnsuites:Array<{room:any;floorIndex:number;source:any}>=[];
 proposed.floors.forEach((floor,floorIndex)=>floor.rooms.forEach(room=>{const source=sourceFor(room,originals);if(isBedroom(room)&&source&&validAnchored(room,source))proposedBedrooms.push({room,floorIndex,id:String(room.id).trim().toLowerCase(),source});if(isEnsuite(room)&&source&&validAnchored(room,source))proposedEnsuites.push({room,floorIndex,source});}));
 proposedBedrooms.forEach(({source,id})=>{const clipId=`source-${id.replace(/[^a-zA-Z0-9_-]/g,"-")}`;defs.push(makeClipPath(clipId,source));});
 proposedBedrooms.forEach(({room,floorIndex,id,source},index)=>{const changed=!originals.has(id)||!sameGeometry(source,room);const clipId=changed?`source-${id.replace(/[^a-zA-Z0-9_-]/g,"-")}`:undefined;const out=renderRoom(room,`Bedroom ${index+1}`,"bedroom",floorIndex,clipId);if(out){overlays.push(out);rendered.add(id);}});
 proposedEnsuites.forEach(({room,floorIndex,source})=>{const out=renderRoom(room,"En-suite","ensuite",floorIndex,undefined);if(out&&validAnchored(room,source))overlays.push(out);});
 for(const change of changes){const id=String(change?.roomId||"").trim().toLowerCase();if(!id||rendered.has(id))continue;const match=proposed.floors.flatMap(f=>f.rooms.map(room=>({room,floor:f}))).find(o=>String(o.room.id).trim().toLowerCase()===id);if(!match||isBedroom(match.room)||isEnsuite(match.room))continue;const source=sourceFor(match.room,originals);if(!source||!validAnchored(match.room,source))continue;const clipId=`source-${id.replace(/[^a-zA-Z0-9_-]/g,"-")}`;defs.push(makeClipPath(clipId,source));const out=renderRoom(match.room,String(match.room.name||match.room.type||"PROPOSED").toUpperCase(),"bedroom",match.floor.level??0,clipId);if(out)overlays.push(out);}
 const finalBedrooms=proposedBedrooms.length,finalEnsuites=proposedEnsuites.length,bannerText=`${finalBedrooms} BEDROOMS  |  ${finalEnsuites} PRIVATE EN-SUITES`,bannerWidth=Math.min(width-30,Math.max(430,bannerText.length*14)),banner=`<g><rect x="15" y="15" width="${bannerWidth}" height="46" rx="10" fill="#14532d" fill-opacity="0.96"/><text x="35" y="45" font-family="Arial,sans-serif" font-size="21" font-weight="900" fill="white">${escapeXml(bannerText)}</text></g>`,legend=`<g><rect x="18" y="${height-54}" width="${Math.min(width-36,610)}" height="36" rx="8" fill="#111827" fill-opacity="0.93"/><circle cx="38" cy="${height-36}" r="7" fill="#facc15"/><text x="52" y="${height-31}" font-family="Arial,sans-serif" font-size="15" font-weight="700" fill="white">BEDROOM</text><circle cx="155" cy="${height-36}" r="7" fill="#38bdf8"/><text x="169" y="${height-31}" font-family="Arial,sans-serif" font-size="15" font-weight="700" fill="white">PRIVATE EN-SUITE</text><text x="360" y="${height-31}" font-family="Arial,sans-serif" font-size="14" font-weight="600" fill="#d1d5db">FINAL VALIDATED GEOMETRY</text></g>`,warning=finalBedrooms===0?`<g><rect x="20" y="70" width="${Math.min(width-40,620)}" height="58" rx="8" fill="#b91c1c" fill-opacity="0.96"/><text x="42" y="107" font-family="Arial,sans-serif" font-size="21" font-weight="800" fill="white">NO VALID BEDROOM GEOMETRY</text></g>`:"";
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs>${defs.join("")}</defs><image href="${escapeXml(originalImageDataUri)}" x="0" y="0" width="${width}" height="${height}" preserveAspectRatio="none"/><g>${overlays.join("")}</g>${banner}${legend}${warning}</svg>`;return`data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}
function sameGeometry(a:any,b:any):boolean{const ap=polygonPoints(a?.polygon),bp=polygonPoints(b?.polygon);return!!ap&&!!bp&&ap===bp;}
