import { NextResponse } from "next/server";
import { openai } from "@/lib/openai";
import { renderFloorPlan } from "@/lib/floorplanRenderer";
import fs from "fs";
import path from "path";
import sharp from "sharp";
import { detectRooms } from "@/lib/floorDetection/detectRooms";
import { detectFloors } from "@/lib/floorDetection/detectFloors";
import { buildOriginalFloorPlan } from "@/lib/floorDetection/buildOriginalFloorPlan";
import { buildHMOAnalysisPrompt } from "@/lib/prompts/hmoAnalysisPrompt";
import { findMaximumHMO, applyBestEnsuites, finalRoomSummary } from "@/lib/hmoPlanner";
import { normaliseHMOReport } from "@/lib/hmoReport";
import { RoomChange, WallSide } from "@/lib/types/floorPlan";

export const runtime = "nodejs";
export const maxDuration = 300;

type RoomLabel = {
  roomId?: string;
  name?: string;
  type?: string;
  floor?: string;
  confidence?: string;
  areaSqm?: number;
  widthM?: number;
  depthM?: number;
  windows?: WallSide[];
  doors?: WallSide[];
  [key: string]: unknown;
};

const WALLS: WallSide[] = ["top", "bottom", "left", "right"];
const norm = (v: unknown) => String(v ?? "").toLowerCase().replace(/[^a-z]/g, "");
const isBedroom = (v: unknown) => norm(v).includes("bedroom") || norm(v).includes("bedroom");
const isBathroom = (v: unknown) => {
  const x = norm(v);
  return x.includes("bath") || x.includes("shower") || x.includes("ensuite") || x.includes("toilet") || x === "wc";
};

function roomIdNumber(id: unknown): number | undefined {
  const matches = String(id ?? "").match(/\d+/g);
  if (!matches?.length) return undefined;
  const value = Number.parseInt(matches[matches.length - 1], 10);
  return Number.isFinite(value) ? value : undefined;
}

function resolveRoom(plan: any, label: RoomLabel): any | undefined {
  const rooms = plan.floors.flatMap((f: any) => f.rooms);
  const requested = String(label.roomId ?? "").trim().toLowerCase();
  if (!requested) return undefined;

  // First honour the exact room id generated by the detector.
  const exact = rooms.find((r: any) => String(r.id).trim().toLowerCase() === requested);
  if (exact) return exact;

  // Vision models commonly return aliases such as room-01, Room 1 or room_001
  // even when the detector emitted room-1. Treat the numeric suffix as the
  // stable identity rather than silently dropping the label.
  const number = roomIdNumber(label.roomId);
  if (number === undefined) return undefined;
  const candidates = rooms.filter((r: any) => roomIdNumber(r.id) === number);
  return candidates.length === 1 ? candidates[0] : undefined;
}

function applyLabels(plan: any, labels: RoomLabel[]): number {
  let applied = 0;
  for (const l of labels) {
    const r = resolveRoom(plan, l);
    if (!r) continue;
    applied += 1;
    if (l.name) r.name = String(l.name);
    if (l.type) r.type = String(l.type);
    if (l.confidence) r.confidence = String(l.confidence);
    if (Number(l.areaSqm) > 0) r.approxAreaSqm = Number(l.areaSqm);
    if (Number(l.widthM) > 0) r.approxWidthM = Number(l.widthM);
    if (Number(l.depthM) > 0) r.approxDepthM = Number(l.depthM);
    if (Array.isArray(l.windows) && l.windows.length > 0) r.windows = l.windows.filter((w): w is WallSide => WALLS.includes(w));
    if (Array.isArray(l.doors) && l.doors.length > 0) r.doors = l.doors.filter((w): w is WallSide => WALLS.includes(w)).map(wall => ({ wall }));
  }
  return applied;
}

function fallbackLabelsFromResult(result: any): RoomLabel[] {
  if (Array.isArray(result.roomLabels)) return result.roomLabels;
  if (Array.isArray(result.rooms)) return result.rooms;
  return [];
}

function cleanJson(s: string) {
  const cleaned = s.replace(/^```json/i, "").replace(/^```/i, "").replace(/```$/i, "").trim();
  try { return JSON.parse(cleaned); } catch {
    const first = cleaned.indexOf("{");
    const last = cleaned.lastIndexOf("}");
    if (first >= 0 && last > first) return JSON.parse(cleaned.slice(first, last + 1));
    throw new Error("The AI analysis did not return valid JSON.");
  }
}

async function classifyRoomsAgain(original: any, image: string): Promise<RoomLabel[]> {
  const roomIds = original.floors.flatMap((f: any) => f.rooms.map((r: any) => ({ id: r.id, floor: f.name })));
  const response = await openai.responses.create({
    model: "gpt-5-mini",
    input: [{ role: "user", content: [
      { type: "input_text", text: `Classify every detected room in this floor-plan image. The red room IDs are authoritative. Return JSON only: {"roomLabels":[{"roomId":"room-1","name":"Bedroom 1","type":"bedroom","floor":"Ground Floor","windows":[],"doors":[]}]}. Use ONLY these room IDs: ${JSON.stringify(roomIds)}. Do not invent rooms. A room whose printed label says Bedroom N must be type bedroom. Living Room/Lounge/Reception is living, Dining Room is dining, Kitchen is kitchen, Shower Room/Bathroom is bathroom, WC/Toilet is WC, Landing/Hall/Entrance/stairs is circulation. Return one item for every supplied room ID.` },
      { type: "input_image", image_url: image, detail: "high" },
    ] }],
  });
  try {
    const parsed = cleanJson(response.output_text || "{}");
    return Array.isArray(parsed.roomLabels) ? parsed.roomLabels : [];
  } catch {
    return [];
  }
}

async function annotate(filePath: string, plan: any) {
  const source = fs.readFileSync(filePath);
  const metadata = await sharp(source).metadata();
  const width = metadata.width || plan.metadata?.imageWidth || 1600;
  const height = metadata.height || plan.metadata?.imageHeight || 1200;
  const annotated = await sharp(source)
    .resize({ width: 1800, height: 1800, fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 76, mozjpeg: true })
    .toBuffer();
  const labels = plan.floors.flatMap((f: any) => f.rooms.map((r: any) =>
    `<rect x="${r.x}" y="${r.y}" width="${r.width}" height="${r.height}" fill="none" stroke="#ff0055" stroke-width="6"/><text x="${r.x + r.width / 2}" y="${r.y + r.height / 2}" text-anchor="middle" font-size="28" font-weight="800" fill="#ff0055" stroke="white" stroke-width="5" paint-order="stroke">${r.id}</text>`
  )).join("\n");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><image href="data:image/jpeg;base64,${annotated.toString("base64")}" width="${width}" height="${height}" preserveAspectRatio="none"/><g>${labels}</g></svg>`;
  const final = await sharp(Buffer.from(svg)).resize({ width: 1800, height: 1800, fit: "inside", withoutEnlargement: true }).jpeg({ quality: 76, mozjpeg: true }).toBuffer();
  return `data:image/jpeg;base64,${final.toString("base64")}`;
}

function appliedLayout(original: any, proposed: any, changes: RoomChange[]): string[] {
  const before = new Map<string, any>(), after = new Map<string, any>(), floors = new Map<string, string>();
  for (const f of original.floors) for (const r of f.rooms) { before.set(r.id, r); floors.set(r.id, f.name); }
  for (const f of proposed.floors) for (const r of f.rooms) { after.set(r.id, r); floors.set(r.id, f.name); }
  const lines: string[] = [];
  for (const c of changes) {
    const b = before.get(c.roomId), a = after.get(c.roomId);
    if (!b || !a) continue;
    const child = after.get(`${c.roomId}-split-2`);
    lines.push(norm(c.action).includes("split") && child
      ? `${floors.get(c.roomId) || "Floor"}: ${a.name || "Bedroom"} retained; ${child.name || "En-suite"} created from the final carved geometry.`
      : `${floors.get(c.roomId) || "Floor"}: ${a.name || a.type || "Room"} converted from ${b.name || b.type || "existing room"}.`);
  }
  return lines.length ? lines : ["No valid proposed geometry was applied."];
}

export async function POST(req: Request) {
  try {
    const { filename, address, propertyType } = await req.json();
    if (!filename || typeof filename !== "string" || /\.\.|[\\/]/.test(filename)) {
      return NextResponse.json({ success: false, error: "Invalid uploaded filename." }, { status: 400 });
    }

    const filePath = path.join(process.cwd(), "public", "uploads", filename);
    if (!fs.existsSync(filePath)) return NextResponse.json({ success: false, error: "Uploaded floor plan not found." }, { status: 404 });

    const floors = await detectFloors(filePath);
    const detectedRooms = await detectRooms(filePath, floors);
    const original = buildOriginalFloorPlan(floors, detectedRooms);
    const meta = await sharp(filePath).metadata();
    original.metadata = { imageWidth: meta.width, imageHeight: meta.height, imageDpi: meta.density };

    if (!original.floors.some((f: any) => f.rooms.length)) {
      return NextResponse.json({ success: false, error: "No rooms were detected in the uploaded floor plan." }, { status: 422 });
    }

    const prompt = buildHMOAnalysisPrompt(address, propertyType)
      .replace("[FLOOR_PLAN_JSON_WILL_BE_INSERTED_HERE]", JSON.stringify(original, null, 2));
    const image = await annotate(filePath, original);

    const response = await openai.responses.create({
      model: "gpt-5",
      input: [{ role: "user", content: [
        { type: "input_text", text: prompt },
        { type: "input_image", image_url: image, detail: "high" },
      ] }],
    });

    const result = cleanJson(response.output_text || "{}");
    const labelled = structuredClone(original);
    let labels = fallbackLabelsFromResult(result);
    let appliedLabelCount = applyLabels(labelled, labels);

    // Never allow a failed/aliased room-label response to turn a real property
    // into a fake "0 bedroom" result. Re-run only the classification step when
    // the first response did not successfully map onto the detected geometry.
    if (appliedLabelCount === 0 || !labelled.floors.flatMap((f: any) => f.rooms).some((r: any) => isBedroom(`${r.type} ${r.name}`))) {
      const retryLabels = await classifyRoomsAgain(original, image);
      const retryApplied = applyLabels(labelled, retryLabels);
      if (retryApplied > 0) {
        labels = retryLabels;
        appliedLabelCount = retryApplied;
      }
    }

    const mappedBedrooms = labelled.floors.flatMap((f: any) => f.rooms).filter((r: any) => isBedroom(`${r.type} ${r.name}`)).length;
    if (mappedBedrooms === 0 && detectedRooms.length > 0) {
      console.error(`ANALYSE ERROR: ${detectedRooms.length} rooms detected but no bedroom labels mapped; refusing to return a false 0-bedroom result.`);
      return NextResponse.json({ success: false, error: "Room recognition completed, but the room labels could not be mapped back to the detected geometry. Please retry the analysis." }, { status: 422 });
    }

    console.log(`HMO room mapping: detected=${detectedRooms.length}, labels=${labels.length}, mapped=${appliedLabelCount}, bedrooms=${mappedBedrooms}`);

    const aiChanges: RoomChange[] = Array.isArray(result.changes)
      ? result.changes.filter((c: any) => c && typeof c.roomId === "string")
      : [];

    const maximum = findMaximumHMO(labelled, aiChanges);
    const ensuites = applyBestEnsuites(maximum.plan, maximum.ensuiteCandidates);
    const proposed = ensuites.plan;
    const appliedChanges = [...maximum.appliedChanges, ...ensuites.applied];
    const rejectedChanges = [...maximum.rejectedChanges, ...ensuites.rejected];

    const final = finalRoomSummary(proposed);
    const current = finalRoomSummary(labelled);
    const currentBedrooms = current.bedrooms;

    const originalImage = `data:${path.extname(filename).toLowerCase() === ".png" ? "image/png" : "image/jpeg"};base64,${fs.readFileSync(filePath).toString("base64")}`;

    const report = normaliseHMOReport(
      result,
      labelled,
      proposed,
      currentBedrooms,
      appliedChanges,
      rejectedChanges,
      address,
      propertyType,
    );

    report.originalFloorPlan = labelled;
    report.proposedFloorPlan = proposed;
    report.changes = appliedChanges;
    report.rejectedChanges = rejectedChanges.map(c => ({
      roomId: c.roomId,
      action: c.action,
      reason: "Rejected by deterministic geometry validation.",
    }));
    report.summary = {
      ...(report.summary || {}),
      bedrooms: currentBedrooms,
      bathrooms: labelled.floors.flatMap((f: any) => f.rooms).filter((r: any) => isBathroom(r.type)).length,
      possibleHMOBedrooms: final.bedrooms,
    };
    report.highestPossibleHMO = {
      ...(report.highestPossibleHMO || {}),
      bedrooms: final.bedrooms,
      ensuites: final.ensuites,
      reason: `Highest bedroom count surviving deterministic geometry validation: ${final.bedrooms}; ${final.ensuites} private ensuites physically applied.`,
    };
    report.geometryFeasibility = {
      ...(report.geometryFeasibility || {}),
      possible: final.bedrooms > 0,
      currentBedrooms,
      proposedBedrooms: final.bedrooms,
      proposedEnsuites: final.ensuites,
      appliedChanges: appliedChanges.length,
      rejectedChanges: rejectedChanges.length,
      finalBedroomIds: final.bedroomIds,
      finalEnsuiteIds: final.ensuiteIds,
    };
    report.recommendedLayout = appliedLayout(labelled, proposed, appliedChanges).length
      ? report.recommendedLayout
      : ["No valid proposed geometry was applied."];
    report.conversionSteps = report.recommendedLayout;
    report.verdict = final.bedrooms > currentBedrooms
      ? `Maximum geometry-feasible ${final.bedrooms}-bedroom HMO layout selected, with ${final.ensuites} private en-suite${final.ensuites === 1 ? "" : "s"}. Planning/licensing/building-control approval still requires professional/local-authority confirmation.`
      : `Final deterministic geometry supports ${final.bedrooms} bedroom${final.bedrooms === 1 ? "" : "s"} and ${final.ensuites} private en-suite${final.ensuites === 1 ? "" : "s"}; no higher-bedroom transformation survived geometry validation.`;
    report.investorSummary = `Final applied geometry contains ${final.bedrooms} bedroom${final.bedrooms === 1 ? "" : "s"} and ${final.ensuites} private en-suite${final.ensuites === 1 ? "" : "s"}. Only successfully applied geometry is reported.`;
    report.generatedLayoutImage = renderFloorPlan(labelled, proposed, originalImage, appliedChanges);

    return NextResponse.json({ success: true, result: report });
  } catch (error: any) {
    console.error("ANALYSE ERROR:", error);
    return NextResponse.json({ success: false, error: error?.message || "Analysis failed on the server." }, { status: 500 });
  }
}
